### ISSUE TITLE
[suggestion] commands to set spawn and home

### ISSUE THREAD

**Issue by jinkhya** [sam-kirby/topoislands#2]
Hello,
could it be possible to add an admin command /topoislands setspawn and add a player command /topoislands sethome please?
Thanks in advance,
Jin

**Comment by sam-kirby** [comment]
Not really; the mod isn't storing any coordinates. It just remembers the ID of the island the player lives on, and calculates where the spawn point for that island would have been when it generated.

For the spawn, it calculates where island ID 0's spawn point would have been.

The mod makes sure players won't spawn in blocks, but otherwise it's up to players/server operators to make sure that they are safe for players to teleport to.
